agent/urls.py
from django.conf.urls import url
from agent.views import AgentContactIndexView, AgentContactTableListView, AgentDetailView, AgentContactCreateView, \
    AgentContactEditView, AgentContactDeleteView, AgentContactCreateModalView
from myhestia.privilege_const import MATTER_CREATE, MATTER_VIEW
from my_tools.decorators import check_staff_perm, back_login_required


urlpatterns = [

    #
    # /agent/
    #
    url(r'^detail/(?P<agent_id>\d+)/$',
        back_login_required(check_staff_perm([MATTER_VIEW])(AgentDetailView.as_view())), name='agent_detail'),

    #
    # agent contact
    #
    url(r'^contact/$',
        back_login_required(check_staff_perm([MATTER_VIEW])(AgentContactIndexView.as_view())),
        name='agent_contact_index'),
    url(r'^contact/table-list/$',
        back_login_required(check_staff_perm([MATTER_VIEW])(AgentContactTableListView.as_view())),
        name='agent_contact_table_list'),

    url(r'^contact/create/$',
        back_login_required(check_staff_perm([MATTER_CREATE])(AgentContactCreateView.as_view())),
        name='agent_contact_create'),

    url(r'^contact/create-modal/$',
        back_login_required(check_staff_perm([MATTER_CREATE])(AgentContactCreateModalView.as_view())),
        name='agent_contact_create_modal'),

    url(r'^contact/edit/(?P<contact_id>\d+)/$',
        back_login_required(check_staff_perm([MATTER_CREATE])(AgentContactEditView.as_view())),
        name='agent_contact_edit'),

    url(r'^contact/delete/(?P<contact_id>\d+)/$',
        back_login_required(check_staff_perm([MATTER_CREATE])(AgentContactDeleteView.as_view())),
        name='agent_contact_delete'),
]

core/urls.py
from django.conf.urls import url

from core.views import DashboardView, StaffTeamIndexView, StaffTeamCreateView, StaffTeamEditView, StaffTeamDeleteView, \
    StaffIndexView, StaffDetailView, StaffCreateView, StaffEditView, StaffInactiveView, StaffActiveView, \
    StaffChangePasswordView, MyProfileEditView, StaffDeleteView
from my_tools.decorators import back_login_required, check_staff_perm
from myhestia.privilege_const import STAFF_VIEW, STAFF_CREATE, STAFF_TEAM_VIEW, STAFF_TEAM_CREATE


urlpatterns = [
    #
    # /back-office/home
    #
    url(r'^$', back_login_required(check_staff_perm([])(DashboardView.as_view())), name='home'),

    #
    # business team
    #
    url(r'^staff-team/$',
        back_login_required(check_staff_perm([STAFF_TEAM_VIEW])(StaffTeamIndexView.as_view())),
        name='staff_team_index'),
    url(r'^staff-team/create/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamCreateView.as_view())),
        name='staff_team_create'),
    url(r'^staff-team/edit/(?P<team_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamEditView.as_view())),
        name='staff_team_edit'),
    url(r'^staff-team/delete/(?P<team_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamDeleteView.as_view())),
        name='staff_team_delete'),

    #
    # staff
    #
    url(r'^staff/$',
        back_login_required(check_staff_perm([STAFF_VIEW])(StaffIndexView.as_view())),
        name='staff_index'),
    url(r'^staff-detail/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_VIEW])(StaffDetailView.as_view())),
        name='staff_detail'),
    url(r'^staff/create/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffCreateView.as_view())),
        name='staff_create'),
    url(r'^staff/edit/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffEditView.as_view())),
        name='staff_edit'),
    url(r'^staff/inactive/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffInactiveView.as_view())),
        name='staff_inactive'),
    url(r'^staff/active/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffActiveView.as_view())),
        name='staff_active'),
    url(r'^staff/delete/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffDeleteView.as_view())),
        name='staff_delete'),

    # change password for me or other staff
    url(r'^staff/change-password/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([])(StaffChangePasswordView.as_view())),
        name='staff_change_password'),

    # edit my profile
    url(r'^staff/my-edit/$',
        back_login_required(check_staff_perm([])(MyProfileEditView.as_view())),
        name='my_profile_edit'),

]

myhestia/urls.py
from django.contrib import admin
from django.conf import settings
from core.views import upload, view_file
from django.conf.urls import include, url
from django.views.static import serve
from django.conf.urls.static import static
from login.views import login_view, login_check, login_out


#
# common URL
#
urlpatterns = [

    url(r'^admin/', admin.site.urls),

    #
    #  media file
    #
    url(r'^media/(?P<path>.*)$', serve, {'document_root': 'media/'}),

    #
    # file upload, download
    #
    url(r'^upload/$', upload, name='upload'),
    url(r'^view-file/(?P<file_uuid>[a-fA-F0-9]{32})/$', view_file, name='view_file'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)


#
# APP URL
#
urlpatterns += [

    #
    # index page
    #
    url(r'^$', login_view, name='index'),

    #
    # login/logout
    #
    url(r'^login/$', login_view, name='login'),
    url(r'^login_check/$', login_check, name='login_check'),
    url(r'^logout/$', login_out, name='logout'),

    #
    # dashboard
    #
    url(r'^home/', include('core.urls')),

    # agent
    url(r'^agent/', include('agent.urls')),

    # client
    url(r'^client/', include('clientdb.urls')),

    # matter
    url(r'^matter/', include('matters.urls')),

    # project
    url(r'^project/', include('project.urls')),

    # notification template
    url(r'^n-template/', include('n_template.urls')),

    #
    url(r'^report/', include('my_report.urls')),

    # bill
    url(r'^bill/', include('my_bill.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

agent/models.py
from __future__ import unicode_literals
from django.db import models
from django.db.models import Q

from matters.models import MatterRecord, MatterNotification


class Agent(models.Model):

    agent_name = models.CharField(max_length=200, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.agent_name

    def get_conveying_matters(self):
        return MatterRecord.objects.filter(~Q(matter_type=MatterRecord.TYPE_OTHER) &
                                           Q(agent_contact__agent=self)).select_related('agent_contact')

    def get_mns(self):
        return MatterNotification.objects.filter(matter__agent_contact__agent=self).distinct()


class AgentContact(models.Model):

    agent = models.ForeignKey('Agent', related_name='agent_contacts')

    contact_name = models.CharField(max_length=128)
    contact_email = models.EmailField()
    contact_mobile = models.CharField(max_length=32)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s (%s, %s)" % (self.contact_name, self.agent.agent_name, self.contact_email,)

agent/views.py
from __future__ import unicode_literals
import json
from django.contrib import messages
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from agent.forms import AgentContactCreateForm, AgentContactEditForm
from agent.models import AgentContact, Agent
from my_tools.datatables import DataTableListView
from my_tools.function import make_a_html, make_span_html
from my_tools.template_tag_app import agent_contact_action_html
from n_template.common import NConst


class AgentDetailView(TemplateView):

    template_name = 'agent/agent_detail.html'

    def get(self, request, *args, **kwargs):

        agent_id = self.kwargs.get('agent_id', 0)
        agent = get_object_or_404(Agent, pk=agent_id)

        data = {
            'agent': agent,
            'NConst': NConst,
        }

        return render(request, self.template_name, data)

    def post(self, request):
        _ = self, request
        raise Http404('Page does not exist')


class AgentContactIndexView(TemplateView):

    template_name = 'agent/agent_contact_index.html'

    def get(self, request, *args, **kwargs):
        data = {}
        return render(request, self.template_name, data)

    def post(self, request):
        _ = self, request
        raise Http404('Page does not exist')


class AgentContactTableListView(DataTableListView):

    table_columns = [
        'pk', 'agent__agent_name', 'contact_name', 'contact_email', 'contact_mobile', '',
    ]

    def get_return_row(self, contact, request):

        id_html = contact.pk

        agent_html = make_a_html(href_url=reverse('agent_detail', args=[contact.agent.pk]),
                                 text=contact.agent.agent_name, tooltip_title=contact.agent.agent_name, trim_length=40)

        contact_html = make_span_html(text=contact.contact_name, tooltip_title=contact.contact_name, trim_length=30)

        email_html = make_span_html(text=contact.contact_email, tooltip_title=contact.contact_email, trim_length=30)

        mobile_html = contact.contact_mobile

        action_html = agent_contact_action_html(contact=contact, request=request)

        return_list = [
            id_html,
            agent_html,
            contact_html,
            email_html,
            mobile_html,
            action_html,
        ]

        return return_list

    def get_object_list(self, request, order_list):

        search_name = request.GET.get('sSearch', '')

        result = AgentContact.objects

        if search_name != '':
            result = result.filter(Q(contact_name__istartswith=search_name) |
                                   Q(agent__agent_name__istartswith=search_name))

        return result.order_by(*order_list).select_related('agent')


class AgentContactCreateView(TemplateView):

    template_name = 'agent/agent_contact_create.html'

    def get(self, request, *args, **kwargs):

        form = AgentContactCreateForm(staff=request.user)

        data = {'form': form}

        return render(request, self.template_name, data)

    def post(self, request):

        form = AgentContactCreateForm(data=request.POST, staff=request.user)

        data = {'form': form}

        if not form.is_valid():
            return render(request, self.template_name, data)

        contact = form.save()

        msg = "Agent contact (%s) is created." % contact.contact_name
        messages.success(request, msg)

        return HttpResponseRedirect(reverse('agent_contact_index'))


class AgentContactCreateModalView(TemplateView):

    template_name = 'agent/_agent_contact_create_modal.html'

    def get(self, request, *args, **kwargs):

        form = AgentContactCreateForm(staff=request.user)

        data = {'form': form}

        return render(request, self.template_name, data)

    def post(self, request):
        _ = self

        if not request.is_ajax():
            raise Http404("Page not exists")

        data = {'status': 'ok'}

        form = AgentContactCreateForm(data=request.POST, staff=request.user)
        if not form.is_valid():
            data['status'] = 'error'
            data['message'] = '<br>'.join(["%s: %s" % (k if k != '__all__' else 'Error', v.as_text(),)
                                           for k, v in form.errors.items()])
            return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')

        contact = form.save()

        data['id'] = contact.pk
        data['text'] = str(contact)

        return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')


class AgentContactEditView(TemplateView):

    template_name = 'agent/agent_contact_edit.html'

    def get(self, request, *args, **kwargs):

        contact_id = self.kwargs.get('contact_id', 0)
        contact = get_object_or_404(AgentContact, pk=contact_id)

        next_url = request.GET.get("next", reverse('agent_contact_index'))

        form = AgentContactEditForm(staff=request.user, instance=contact)

        data = {
            'form': form,
            'next': next_url,
        }

        return render(request, self.template_name, data)

    def post(self, request, contact_id):

        contact = get_object_or_404(AgentContact, pk=contact_id)

        next_url = request.GET.get("next", reverse('agent_contact_index'))

        form = AgentContactEditForm(staff=request.user, data=request.POST, instance=contact)

        data = {
            'form': form,
            'next': next_url,
        }

        # validate failed
        if not form.is_valid():
            return render(request, self.template_name, data)

        contact = form.save()

        msg = "Agent contact (%s) is updated." % contact.contact_name
        messages.success(request, msg)

        return HttpResponseRedirect(next_url)


class AgentContactDeleteView(TemplateView):

    """
        delete (ajax post)
    """
    def get(self, request, *args, **kwargs):
        raise Http404('Page does not exist')

    def post(self, request, contact_id=0):
        _ = self

        if not request.is_ajax() or contact_id == 0:
            raise Http404("Page not exists")

        next_url = request.GET.get("next", reverse('agent_contact_index'))

        contact = get_object_or_404(AgentContact, pk=contact_id)

        data = {
            'status': 'ok',
            'next': next_url,
        }

        # check
        if contact.agent_contact_matters.exists():
            data['status'] = 'error'
            data['message'] = 'Can NOT delete this contact. Some matter is using it.'
            return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')

        AgentContact.objects.filter(pk=contact_id).delete()

        messages.success(request, "Agent contact (%s) is deleted." % contact.contact_name)

        return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')

templates/agent/_agent_contact_create_modal.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Create Agent Contact</h4>
</div>


<form action="{% url 'agent_contact_create_modal' %}" enctype="multipart/form-data" method="post" id='agent-contact-create-frm'>
    {% csrf_token %}

    <div class="modal-body">
        <div class="form-group row">
            <div class="col-sm-8 control-group">
                <label for="agent_name"><span class="txt-color-red">* </span>Agent Name</label>
                <input type="text" name="agent_name" class="form-control autocomplete"
                       value="{{ form.agent_name.value | default:''}}"
                       data-autocomplete='{{ form.agent_list|list2js_array }}'
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="200">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-8 control-group">
                <label for="contact_name"><span class="txt-color-red">* </span>Contact Name</label>
                <input type="text" name="contact_name" class="form-control"
                       value="{{ form.contact_name.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="128">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4 control-group">
                <label for="contact_email"><span class="txt-color-red">* </span>Contact Email</label>
                <input type="text" name="contact_email" class="form-control"
                       value="{{ form.contact_email.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-emailaddress="true"
                       data-bv-emailaddress-message="* Please input valid email"
                       data-bv-stringlength="true" maxlength="254">
            </div>
            <div class="col-sm-4 control-group">
                <label for="contact_mobile"><span class="txt-color-red">* </span>Contact Mobile</label>
                <input type="text" name="contact_mobile" class="form-control"
                       value="{{ form.contact_mobile.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32"
                       data-bv-regexp="true"
                       data-bv-regexp-regexp='^[0-9]{8,}$'
                       data-bv-regexp-message="Please input valid mobile">
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="button button-flat" data-dismiss="modal">
            Cancel
        </button>
        <button type="submit" class="button button-flat-primary" data-ok-msg="Agent contact is added.">
            Create Agent Contact
        </button>
    </div>
</form>


<script>

$(function(){


pageSetUp();

})

</script>

templates/agent/agent_contact_create.html
{% extends 'mainbase.html' %}

{% block title %} Create Agent Contact {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb_url 'Agent Contact' 'agent_contact_index' %}
    {% breadcrumb 'Create Agent Contact' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Create Agent Contact
        <i class="pull-right f11p mt5"><span class="txt-color-red">* </span>compulsory fields</i>
    </h4>
    <hr class="dash mt10">

    <form action="{% url 'agent_contact_create' %}" enctype="multipart/form-data" method="post" id='frm' >
        {% csrf_token %}

        <div class="form-group row">
            <div class="col-lg-4 col-md-6 col-sm-8 control-group">
                <label for="agent_name"><span class="txt-color-red">* </span>Agent Name</label>
                <input type="text" name="agent_name" class="form-control autocomplete"
                       value="{{ form.agent_name.value | default:''}}"
                       data-autocomplete='{{ form.agent_list|list2js_array }}'
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="200">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-lg-4 col-md-6 col-sm-8 control-group">
                <label for="contact_name"><span class="txt-color-red">* </span>Contact Name</label>
                <input type="text" name="contact_name" class="form-control"
                       value="{{ form.contact_name.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="128">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-2 col-md-3 col-sm-4 control-group">
                <label for="contact_email"><span class="txt-color-red">* </span>Contact Email</label>
                <input type="text" name="contact_email" class="form-control"
                       value="{{ form.contact_email.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-emailaddress="true"
                       data-bv-emailaddress-message="* Please input valid email"
                       data-bv-stringlength="true" maxlength="254">
            </div>
            <div class="col-lg-2 col-md-3 col-sm-4 control-group">
                <label for="contact_mobile"><span class="txt-color-red">* </span>Contact Mobile</label>
                <input type="text" name="contact_mobile" class="form-control"
                       value="{{ form.contact_mobile.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32"
                       data-bv-regexp="true"
                       data-bv-regexp-regexp='^[0-9]{8,}$'
                       data-bv-regexp-message="Please input valid mobile">
            </div>
        </div>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-12">
                    <button class="button button-flat-primary" type="submit">
                        Create Agent Contact
                    </button>
                </div>
            </div>
        </div>

    </form>
</div>

{% endblock %}


{% block jscript %}

<script>

$(function(){
    /**
     * form validation
     */
    $('#frm').bootstrapValidator({
        trigger: 'change keyup',
        group: '.control-group'
    });
})

</script>


{% endblock %}

templates/agent/agent_contact_edit.html
{% extends 'mainbase.html' %}

{% block title %} Edit Agent Contact {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb_url 'Agent Contact' 'agent_contact_index' %}
    {% breadcrumb 'Edit Agent Contact' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Edit Agent Contact - {{ form.instance.agent.agent_name }}
        <i class="pull-right f11p mt5"><span class="txt-color-red">* </span>compulsory fields</i>
    </h4>
    <hr class="dash mt10">

    <form action="{% url 'agent_contact_edit' contact_id=form.instance.pk %}?next={{ next }}" enctype="multipart/form-data" method="post" id='frm'>
        {% csrf_token %}

        <div class="form-group row">
            <div class="col-lg-4 col-md-6 col-sm-8 control-group">
                <label for="contact_name"><span class="txt-color-red">* </span>Contact Name</label>
                <input type="text" name="contact_name" class="form-control"
                       value="{{ form.contact_name.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="128">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-2 col-md-3 col-sm-4 control-group">
                <label for="contact_email"><span class="txt-color-red">* </span>Contact Email</label>
                <input type="text" name="contact_email" class="form-control"
                       value="{{ form.contact_email.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-emailaddress="true"
                       data-bv-emailaddress-message="* Please input valid email"
                       data-bv-stringlength="true" maxlength="254">
            </div>
            <div class="col-lg-2 col-md-3 col-sm-4 control-group">
                <label for="contact_mobile"><span class="txt-color-red">* </span>Contact Mobile</label>
                <input type="text" name="contact_mobile" class="form-control"
                       value="{{ form.contact_mobile.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32"
                       data-bv-regexp="true"
                       data-bv-regexp-regexp='^[0-9]{8,}$'
                       data-bv-regexp-message="Please input valid mobile">
            </div>
        </div>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-12">
                    <button class="button button-flat-primary" type="submit">
                        Update Agent Contact
                    </button>
                </div>
            </div>
        </div>

    </form>
</div>

{% endblock %}


{% block jscript %}

<script>

$(function(){
    /**
     * form validation
     */
    $('#frm').bootstrapValidator({
        trigger: 'change keyup',
        group: '.control-group'
    });
})

</script>


{% endblock %}

templates/agent/agent_contact_index.html
{% extends 'mainbase.html' %}

{% block title %} Agent Contact {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb 'Agent Contact' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Agent Contact
        {% if request|check_pv:'MATTER_CREATE'%}
            <span class="pull-right">
                <a href="{% url 'agent_contact_create' %}" class="button button-flat-primary">
                    <i class="fa fa-plus f11p" aria-hidden="true"></i> Create Agent Contact
                </a>
            </span>
        {% endif %}
    </h4>
    <hr class="dash mt15">

    <div class="row">
        <div class="col-lg-2 col-md-3 col-sm-4">
            <div class="input-icon-right">
                <i class="glyphicon glyphicon-search"></i>
                <input type="text" id="search-input" name="search_name" class="form-control" placeholder="Agent/Contact Name">
            </div>
        </div>
    </div>

    <div class="mt10 table-responsive">
        <table class="table table-striped my-table" id="contact-table" width="100%"
               data-server-url="{% url 'agent_contact_table_list' %}">
            <thead>
                <tr class="">
                    <th class="unsearchable">ID</th>
                    <th class="unsorted">Agent</th>
                    <th class="unsorted">Contact</th>
                    <th class="unsearchable unsorted">Email</th>
                    <th class="unsearchable unsorted">Mobile</th>
                    <th class="unsearchable unsorted text-center" width="80">Actions</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

</div>

{% endblock %}


{% block jscript %}
<script>

$(function(){

    JLib.init_data_table('#contact-table', true, 'search-input', 0);

})
</script>

<script src="{{ STATIC_URL }}js/agent_contact_action.js?version=1.0.0"></script>

{% endblock %}

templates/agent/agent_detail.html
{% extends 'mainbase.html' %}
{% load humanize %}

{% block title %} Agent Detail {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb_url 'Agent Contact' 'agent_contact_index' %}
    {% breadcrumb 'Agent Detail' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">Agent Detail</h4>
    <hr class="dash mt10">

    <div class="row detail-panel">
        <div class="col-sm-12">
            <dl class="dl-horizontal">
                <dt>ID</dt>
                <dd>{{ agent.pk }}</dd>
                <dt>Agent Name</dt>
                <dd>{{ agent.agent_name }}</dd>
                <dt>Created At</dt>
                <dd>
                    {{ agent.created_at|date:"d/m/Y H:i" }}
                </dd>
            </dl>
        </div>
    </div>
</div>

<div class="jarviswidget plain-tab-panel mt20">
    <header>
        <ul class="nav nav-tabs pull-left in" id="tab-head">
            <li class="active">
                <a data-toggle="tab" href="#contact"><span class="">Agent Contacts</span></a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#c-matter"><span class="">Agent Conveying Matters</span></a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#n"><span class="">Notifications</span></a>
            </li>
        </ul>
    </header>

    <div class="widget-body">
        <div class="tab-content padding-10">
            <div class="tab-pane active" id="contact">
                <div class="table-responsive">
                    <table class="table table-striped my-table" id="agent-contact-table">
                        <thead>
                            <tr>
                                <th class="unsearchable unsorted">ID</th>
                                <th class="unsearchable">Contact</th>
                                <th class="unsearchable unsorted">Email</th>
                                <th class="unsearchable unsorted">Mobile</th>
                                <th class="unsearchable unsorted">Created At</th>
                                <th class="unsearchable unsorted text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in agent.agent_contacts.all %}
                                <tr>
                                    <td>{{ c.pk }}</td>
                                    <td>{{ c.contact_name }}</td>
                                    <td>{{ c.contact_email }}</td>
                                    <td>{{ c.contact_mobile }}</td>
                                    <td>{{ c.created_at|date:"d/m/Y H:i" }}</td>
                                    <td>
                                        {% agent_contact_action_html contact=c request=request %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tab-pane" id="c-matter">
                {% include 'matter/_matter_table_conveying.html' with matters=agent.get_conveying_matters %}
            </div>
            <div class="tab-pane" id="n">
                {% include 'matter/_matter_notification_table.html' with mns=agent.get_mns NConst=NConst %}
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block jscript %}

<script>

$(function(){
    JLib.init_data_table('#agent-contact-table', true, '', 0);

    JLib.init_data_table('#conveying-matter-table', true, '');
    JLib.init_data_table('#mn-table', true, '', 1);
})

</script>
<script src="{{ STATIC_URL }}js/matter_action.js?version=1.0.1"></script>
<script src="{{ STATIC_URL }}js/agent_contact_action.js?version=1.0.0"></script>
<script src="{{ STATIC_URL }}js/matter_notification_action.js?version=1.0.0"></script>

{% endblock %}