core/urls.py
from django.conf.urls import url

from core.views import DashboardView, StaffTeamIndexView, StaffTeamCreateView, StaffTeamEditView, StaffTeamDeleteView, \
    StaffIndexView, StaffDetailView, StaffCreateView, StaffEditView, StaffInactiveView, StaffActiveView, \
    StaffChangePasswordView, MyProfileEditView, StaffDeleteView
from my_tools.decorators import back_login_required, check_staff_perm
from myhestia.privilege_const import STAFF_VIEW, STAFF_CREATE, STAFF_TEAM_VIEW, STAFF_TEAM_CREATE


urlpatterns = [
    #
    # /back-office/home
    #
    url(r'^$', back_login_required(check_staff_perm([])(DashboardView.as_view())), name='home'),

    #
    # business team
    #
    url(r'^staff-team/$',
        back_login_required(check_staff_perm([STAFF_TEAM_VIEW])(StaffTeamIndexView.as_view())),
        name='staff_team_index'),
    url(r'^staff-team/create/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamCreateView.as_view())),
        name='staff_team_create'),
    url(r'^staff-team/edit/(?P<team_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamEditView.as_view())),
        name='staff_team_edit'),
    url(r'^staff-team/delete/(?P<team_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamDeleteView.as_view())),
        name='staff_team_delete'),

    #
    # staff
    #
    url(r'^staff/$',
        back_login_required(check_staff_perm([STAFF_VIEW])(StaffIndexView.as_view())),
        name='staff_index'),
    url(r'^staff-detail/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_VIEW])(StaffDetailView.as_view())),
        name='staff_detail'),
    url(r'^staff/create/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffCreateView.as_view())),
        name='staff_create'),
    url(r'^staff/edit/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffEditView.as_view())),
        name='staff_edit'),
    url(r'^staff/inactive/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffInactiveView.as_view())),
        name='staff_inactive'),
    url(r'^staff/active/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffActiveView.as_view())),
        name='staff_active'),
    url(r'^staff/delete/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffDeleteView.as_view())),
        name='staff_delete'),

    # change password for me or other staff
    url(r'^staff/change-password/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([])(StaffChangePasswordView.as_view())),
        name='staff_change_password'),

    # edit my profile
    url(r'^staff/my-edit/$',
        back_login_required(check_staff_perm([])(MyProfileEditView.as_view())),
        name='my_profile_edit'),

]

myhestia/urls.py
from django.contrib import admin
from django.conf import settings
from core.views import upload, view_file
from django.conf.urls import include, url
from django.views.static import serve
from django.conf.urls.static import static
from login.views import login_view, login_check, login_out


#
# common URL
#
urlpatterns = [

    url(r'^admin/', admin.site.urls),

    #
    #  media file
    #
    url(r'^media/(?P<path>.*)$', serve, {'document_root': 'media/'}),

    #
    # file upload, download
    #
    url(r'^upload/$', upload, name='upload'),
    url(r'^view-file/(?P<file_uuid>[a-fA-F0-9]{32})/$', view_file, name='view_file'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)


#
# APP URL
#
urlpatterns += [

    #
    # index page
    #
    url(r'^$', login_view, name='index'),

    #
    # login/logout
    #
    url(r'^login/$', login_view, name='login'),
    url(r'^login_check/$', login_check, name='login_check'),
    url(r'^logout/$', login_out, name='logout'),

    #
    # dashboard
    #
    url(r'^home/', include('core.urls')),

    # agent
    url(r'^agent/', include('agent.urls')),

    # client
    url(r'^client/', include('clientdb.urls')),

    # matter
    url(r'^matter/', include('matters.urls')),

    # project
    url(r'^project/', include('project.urls')),

    # notification template
    url(r'^n-template/', include('n_template.urls')),

    #
    url(r'^report/', include('my_report.urls')),

    # bill
    url(r'^bill/', include('my_bill.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

core/models.py
from __future__ import unicode_literals

from PIL import Image
import os
import uuid
import StringIO
from django.contrib.auth.models import User
from django.core.files import File
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import models
from core.commons import CommonConst
from matters.models import MatterDocument
from myhestia.global_const import THUMBNAIL_SIZE, MD_THUMBNAIL_SIZE
from myhestia.privilege_const import STAFF_POSITIONS
from myhestia.settings import TMP_FILE_ROOT
from my_tools.storage_engine import make_file_path, GlobalStorage


class Staff(User):

    USER_TYPE_STAFF = 'S'
    USER_TYPE_SYSADMIN = 'A'
    USER_TYPE = ((USER_TYPE_STAFF, 'Staff'), (USER_TYPE_SYSADMIN, 'Sys Admin'),)

    STATUS_INACTIVE = 'I'
    STATUS_ACTIVE = 'A'
    STATUS_CHOICE = ((STATUS_INACTIVE, 'Inactive'), (STATUS_ACTIVE, 'Active'),)

    #
    # Business organization and system privileges
    #
    #   - line_manager, team and is_team_head describe business organization (only for display)
    #   - StaffPosition is for privileges in this system
    #   - user_type is simply to identity different user
    #
    # privilege has no relationship with business organization
    #
    user_type = models.CharField(max_length=1, choices=USER_TYPE, default=USER_TYPE_STAFF)

    # one staff only has one line manager
    line_manager = models.ForeignKey('core.Staff', blank=True, null=True, related_name='my_members')

    # one staff only belongs to one team
    team = models.ForeignKey('core.StaffTeam', related_name='team_members')

    # only 2 management level for each team - head and member, because most of agencies are small businesses
    is_team_head = models.BooleanField(default=False, blank=True)

    status = models.CharField(max_length=1, default=STATUS_ACTIVE, choices=STATUS_CHOICE)

    en_nickname = models.CharField(max_length=64)
    gender = models.CharField(max_length=8, default=CommonConst.GENDER_UNKNOWN, choices=CommonConst.GENDER_CHOICE)
    mobile = models.CharField(max_length=32, default='')
    personal_email = models.CharField(max_length=128, blank=True, default='')
    join_date = models.DateField(blank=True, null=True)
    dob = models.DateField(blank=True, null=True)

    notes = models.TextField(blank=True, default='')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff'

    def __unicode__(self):
        return '%s %s (%s, ID: %s)' % (self.en_nickname, self.last_name, self.team, self.pk,)

    def get_full_name(self):
        return ' '.join([self.first_name, self.last_name]).title()

    def get_full_en_name(self):
        if self.en_nickname:
            return ' '.join([self.en_nickname, self.last_name]).title()
        else:
            return self.get_full_name()

    def get_short_desc(self):
        if self.en_nickname:
            return self.en_nickname.title()

        return self.first_name.title()

    def get_active_positions(self):
        return StaffPosition.objects.filter(staff=self, is_active=True)

    def get_active_position_desc(self):
        return ', '.join([p.get_position_display() for p in self.get_active_positions()])


class StaffPosition(models.Model):

    staff = models.ForeignKey('Staff', related_name='staff_positions')
    position = models.IntegerField(choices=STAFF_POSITIONS)
    is_active = models.BooleanField(blank=True, default=False)
    hr_notes = models.TextField(blank=True, default='')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.get_position_display()


class StaffTeam(models.Model):
    """
        Business organization
            - each staff must belong to one and only one business team
    """
    team_name = models.CharField(max_length=128, unique=True)
    parent_team = models.ForeignKey('core.StaffTeam', related_name='child_teams', null=True, blank=True)
    # start from 0
    level = models.PositiveSmallIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.team_name


class GlobalFile(models.Model):
    """
        All files
    """
    TYPE_THUMBNAIL_SM = 'thumbnail_sm'
    TYPE_THUMBNAIL_MD = 'thumbnail_md'

    TYPE_MANUAL_ATTACHMENT = 'attachment'
    TYPE_CHOICE = (
        (TYPE_MANUAL_ATTACHMENT, 'Attachment'),
    )

    FILE_TYPES = TYPE_CHOICE + MatterDocument.TYPE_CHOICE

    id = models.AutoField(primary_key=True)

    file_type = models.CharField(max_length=32, choices=FILE_TYPES)
    related_model_id = models.PositiveIntegerField(default=0)

    uuid = models.CharField(max_length=32, default='', unique=True)
    file = models.FileField(blank=True, upload_to=make_file_path, storage=GlobalStorage, max_length=255)
    file_ext = models.CharField(max_length=10, default='')
    notes = models.TextField(blank=True, default='')

    thumbnail = models.ForeignKey('core.GlobalFile', related_name='thumbnail_files', blank=True, null=True)
    md_thumbnail = models.ForeignKey('core.GlobalFile', related_name='md_thumbnail_files', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s: %s' % (self.id, self.get_file_type_display())

    def save(self, *args, **kwargs):
        # in v1.0, Thumbnail is not necessary.
        need_thumbnail = kwargs.get('need_thumbnail', False)
        if need_thumbnail and self.file_type not in [GlobalFile.TYPE_THUMBNAIL_SM, GlobalFile.TYPE_THUMBNAIL_MD]:
            self.thumbnail, self.md_thumbnail = self.make_thumbnail()

        super(GlobalFile, self).save(*args, **kwargs)

    def is_image(self):
        return self.file_ext.lower() in ['bmp', 'jpeg', 'jpg', 'jpe', 'png']

    @staticmethod
    def make_from_tmp(file_name, file_type, related_model_id=0):
        """
        Save file from temporary file in path TMP_FILE_ROOT

        Args:
            file_name - file name, like xxx.jpg
            file_type - ref. GlobalFile. FILE_TYPES

        Returns:
            GlobalFile instance

        """
        global_file = GlobalFile()
        global_file.related_model_id = related_model_id
        global_file.uuid = uuid.uuid4().hex
        global_file.file_type = file_type
        global_file.file_ext = file_name.split('.')[-1]

        #
        # save file to database.
        # whatever destination file name is, storage engine will recalculate it from uuid
        # ref. core.storage_engine.py
        #
        full_name = os.path.join(TMP_FILE_ROOT, file_name)
        tmp_file_content = File(open(full_name, 'rb'))
        global_file.file.save(file_name, tmp_file_content, save=True)
        global_file.save()

        return global_file

    def make_thumbnail(self):
        if not self.is_image():
            return None, None

        image = Image.open(self.file.name)

        # Convert to RGB if necessary
        if image.mode not in ('L', 'RGB'):
            image = image.convert('RGB')

        # We use our PIL Image object to create the thumbnail, which already
        # has a thumbnail() convenience method that contains proportions.
        # Additionally, we use Image. ANTIALIAS to make the image look better.
        # Without antialiasing the image pattern artifacts may result.
        image.thumbnail(MD_THUMBNAIL_SIZE, Image.ANTIALIAS)

        temp_handle = StringIO.StringIO()
        image.save(temp_handle, 'png')
        temp_handle.seek(0)

        # Save to the thumbnail field
        suf = SimpleUploadedFile(os.path.split(self.file.name)[-1],
                                 temp_handle.read(), content_type='image/png')

        md_global_file = GlobalFile()
        md_global_file.uuid = uuid.uuid4().hex
        md_global_file.file_type = GlobalFile.TYPE_THUMBNAIL_MD
        md_global_file.file_ext = 'png'

        md_global_file.file.save(suf.name + '.png', suf, save=True)

        md_global_file.save()

        image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

        temp_handle = StringIO.StringIO()
        image.save(temp_handle, 'png')
        temp_handle.seek(0)

        # Save to the thumbnail field
        suf = SimpleUploadedFile(os.path.split(self.file.name)[-1],
                                 temp_handle.read(), content_type='image/png')

        sm_global_file = GlobalFile()
        sm_global_file.uuid = uuid.uuid4().hex
        sm_global_file.file_type = GlobalFile.TYPE_THUMBNAIL_SM
        sm_global_file.file_ext = 'png'

        sm_global_file.file.save(suf.name + '.png', suf, save=True)

        sm_global_file.save()

        return sm_global_file, md_global_file

templates/core/dashboard.html
{% extends 'mainbase.html' %}
{% load humanize %}

{% block title %} Dashboard {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
{% endblock %}

{% block content %}

{% if request|check_pv:'REPORT_VIEW' %}
    <section id="widget-grid" class="">
        <div class="row mt10">
            <article class="col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget " data-widget-colorbutton="false" data-widget-editbutton="false"
                    data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-custombutton="false" data-widget-collapsed="false" data-widget-sortable="false">

                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2>Stamp Duty Due Notification - In 30 days</h2>
                        <div class="widget-toolbar">
                            <a aria-expanded="false" class="txt-color-blueDark" href="{% url 'report_stamp_duty_notification_download' %}">
                                Download Excel
                            </a>
                        </div>
                    </header>

                    <div class="widget-body">
                        {% include 'matter/_matter_notification_table_report.html' with mns=due_mns %}
                    </div>
                </div>
            </article>
        </div>
    </section>
{% endif %}

{% if request|check_pv:'MATTER_VIEW' %}
    <div class="plain-panel">
        <h5 class="mt0">
            My Settlement In 30 Days
            <a href="{% url 'matter_index' %}" class="pull-right f12p">view all >></a>
        </h5>
        {% include 'matter/_matter_table_conveying.html' with matters=settle_matters %}
    </div>
{% endif %}

{% endblock %}

{% block jscript %}

<script>

$(function(){
    JLib.init_data_table('#conveying-matter-table', true, '');

    JLib.init_data_table('#mn-table-report', true, '', 7);
})

</script>

<script src="{{ STATIC_URL }}js/matter_action.js?version=1.0.1"></script>

{% endblock %}

templates/core/my_profile_edit.html
{% extends 'mainbase.html' %}

{% block title %} Edit Staff {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb 'Edit Profile' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Edit Profile
        <i class="pull-right f11p mt5"><span class="txt-color-red">* </span>compulsory fields</i>
    </h4>
    <hr class="dash mt10">

    <form action="{% url 'my_profile_edit' %}" enctype="multipart/form-data" method="post" id='frm'>
        {% csrf_token %}
        <div class="form-group row">
            <div class="col-sm-3 control-group">
                <label for="username"><span class="txt-color-red">* </span>
                    Username <i class="note txt-color-blue ml5">as login account</i>
                </label>
                <input type="text" name="username" class="form-control" readonly
                       value="{{ form.instance.username | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="30">

            </div>
            <div class="col-sm-3 control-group">
                <label for="email"><span class="txt-color-red">* </span>Email</label>
                <input type="text" name="email" class="form-control" readonly
                       value="{{ form.instance.email | default:''}}"
                       data-bv-notempty="true"
                       data-bv-emailaddress="true"
                       data-bv-emailaddress-message="* Please input valid email"
                       data-bv-stringlength="true" maxlength="128">

            </div>
        </div>

        <h4 class="mt30">Basic Information</h4>
        <hr class="dash mt10">
        <div class="form-group row">
            <div class="col-sm-2 control-group">
                <label for="first_name"><span class="txt-color-red">* </span>First Name</label>
                <input type="text" name="first_name" class="form-control" readonly
                       value="{{ form.instance.first_name | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32">
            </div>
            <div class="col-sm-2 control-group">
                <label for="last_name"><span class="txt-color-red">* </span>Last Name</label>
                <input type="text" name="last_name" class="form-control" readonly
                       value="{{ form.instance.last_name | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32">
            </div>
            <div class="col-sm-2 control-group">
                <label for="en_nickname"><span class="txt-color-red">* </span>English Name</label>
                <input type="text" name="en_nickname" class="form-control"
                       value="{{ form.en_nickname.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-3 control-group">
                <label for="mobile"><span class="txt-color-red">* </span>Mobile</label>
                <input type="text" name="mobile" class="form-control"
                       value="{{ form.mobile.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="32"
                       data-bv-regexp="true"
                       data-bv-regexp-regexp='^[0-9]{8,}$'
                       data-bv-regexp-message="Please input valid phone number">
            </div>
            <div class="col-sm-3 control-group">
                <label for="personal_email"><span class="txt-color-red">* </span>Personal Email</label>
                <input type="text" name="personal_email" class="form-control"
                       value="{{ form.personal_email.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-emailaddress="true"
                       data-bv-emailaddress-message="* Please input valid email"
                       data-bv-stringlength="true" maxlength="128">

            </div>
        </div>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-12">
                    <button class="button button-flat-primary" type="submit">
                        Update Profile
                    </button>
                </div>
            </div>
        </div>

    </form>


</div>


{% endblock %}


{% block jscript %}

<script>

$(function(){
    /**
     * form validation
     */
    $('#frm').bootstrapValidator({
        trigger: 'change keyup',
        group: '.control-group'
    });

})

</script>


{% endblock %}

templates/core/staff_detail.html
{% extends 'mainbase.html' %}

{% block title %} Staff Detail {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb_url 'Staff' 'staff_index' %}
    {% breadcrumb 'Staff Detail' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Staff Detail
        <span class="pull-right">
            {% staff_action_html staff=staff request=request html_type='btn' %}
        </span>
    </h4>
    <hr class="dash mt15">

    <div class="row detail-panel">
        <div class="col-sm-6">
            <dl class="dl-horizontal mb30">
                <dt>ID</dt>
                <dd>{{ staff.pk }}</dd>
                <dt>Login Username</dt>
                <dd>{{ staff.username }}</dd>
                <dt>Name</dt>
                <dd class="txt-color-green"><b>{{ staff.get_short_desc }}</b></dd>
                <dt>Email</dt>
                <dd>
                    <a href="mailto:{{ staff.email }}">{{ staff.email }}</a>
                </dd>
                <dt>Mobile Phone</dt>
                <dd>{{ staff.mobile|insert_space_mobile }}</dd>
                <dt>Personal Email</dt>
                <dd>
                    <a href="mailto:{{ staff.personal_email }}">{{ staff.personal_email }}</a>
                </dd>
                <dt>Join Date</dt>
                <dd>{{ staff.join_date | date:'d/m/Y' }}</dd>
                <dt>Date of Birth</dt>
                <dd>{{ staff.dob|date:'d/m/Y' }}</dd>
                <dt>Gender</dt>
                <dd>
                    <span class="{% get_gender_class gender=staff.gender %}">
                        {{ staff.get_gender_display }}
                    </span>
                </dd>
            </dl>
        </div>
        <div class="col-sm-6">
            <dl class="dl-horizontal">
                <dt>Status</dt>
                <dd>
                    <span class="{% user_status_bg_class staff=staff %}">{{ staff.get_status_display }}</span>
                </dd>
                <dt>Team</dt>
                <dd>{{ staff.team.team_name }}</dd>
                <dt>Is Team Head</dt>
                <dd>{{ staff.is_team_head | yesno:'Yes,No' }}</dd>
                <dt>Line Manager</dt>
                <dd>
                    {% if staff.line_manager %}
                        <a href="{% url 'staff_detail' user_id=staff.line_manager.pk %}"
                           rel="tooltip" data-placement="bottom" data-html="true"
                           data-original-title="{{ staff.line_manager.get_short_desc }}">
                            {{ staff.line_manager.get_short_desc|truncatechars:20 }}
                        </a>
                    {% endif %}
                </dd>
                <dt>Staff Positions</dt>
                <dd class="txt-color-green">
                    {% for p in staff.get_active_positions %}
                        {{ p.get_position_display }}
                        {% if not forloop.last %} <br> {% endif %}
                    {% endfor %}
                </dd>
            </dl>
        </div>
    </div>
</div>


{% endblock %}


{% block jscript %}

<script>

$(function(){

})

</script>
    
<script src="{{ STATIC_URL }}js/staff_action.js?version=1.0.0"></script>

{% endblock %}

templates/core/staff_index.html
{% extends 'mainbase.html' %}

{% block title %} Staff {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb 'Staff' %}
{% endblock %}

{% block content %}

<div class="jarviswidget plain-tab-panel mt10">
    <header>
        <ul class="nav nav-tabs pull-left in" id="tab-head">
            <li class="active">
                <a data-toggle="tab" href="#s1"><span class="">Staff List</span></a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#s2"><span class="text-info">Reporting Relationships</span></a>
            </li>
        </ul>
    </header>

    <div class="widget-body">
        <div id="myTabContent1" class="tab-content padding-10">
            <div class="tab-pane active" id="s1">
                <div class="row">
                    <div class="col-lg-2 col-md-3 col-sm-4 pr0">
                        <div class="input-icon-right">
                            <i class="glyphicon glyphicon-search"></i>
                            <input type="text" id="search-input" name="search" class="form-control" placeholder="Name/Email">
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-3 col-sm-4 pr0">
                        <select class="form-control" name="team" id="team">
                            <option value="{% url 'staff_index' %}">ALL Teams</option>
                            {% for team in teams  %}
                                <option value="{% url 'staff_index' %}?team_id={{ team.pk }}"
                                        {% if team_id|safe == team.pk|safe %}selected{% endif %}>{{ team.team_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-8 col-md-6 col-sm-4">
                        {% if request|check_pv:'STAFF_CREATE'%}
                            <span class="pull-right mb5">
                                <a href="{% url 'staff_create' %}" class="button button-flat-primary"><i class="fa fa-plus f11p" aria-hidden="true"></i> Create Staff</a>
                            </span>
                        {% endif %}
                    </div>
                </div>

                <div class="mt10 table-responsive">
                    <table class="table table-striped my-table" id="content-table" width="100%">
                        <thead>
                            <tr class="">
                                <th class="unsearchable">ID</th>
                                <th class="unsearchable unsorted">Username</th>
                                <th class="unsorted">Name</th>
                                <th class="unsorted">Email</th>
                                <th class="unsearchable unsorted">Mobile</th>
                                <th class="unsearchable unsorted">Personal Email</th>
                                <th class="unsearchable unsorted">Team</th>
                                <th class="unsearchable unsorted">Position</th>
                                <th class="unsearchable unsorted">Status</th>
                                <th class="unsearchable unsorted text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for staff in staff_list %}
                            <tr>
                                <td>{{ staff.pk }}</td>
                                <td>
                                    <a href="{% url 'staff_detail' user_id=staff.pk %}">
                                        {{ staff.username }}
                                    </a>
                                </td>
                                <td>
                                    <span rel="tooltip" data-placement="bottom" data-html="true"
                                          data-original-title="{{ staff.get_short_desc }}">
                                        {{ staff.get_short_desc | truncatechars:25 }}
                                    </span>
                                </td>
                                <td>
                                    <a rel="tooltip" data-placement="bottom" data-html="true"
                                       data-original-title="{{ staff.email }}" href="mailto:{{ staff.email }}">
                                        {{ staff.email | truncatechars:30 }}
                                    </a>
                                </td>
                                <td>{{ staff.mobile|insert_space_mobile }}</td>
                                <td>
                                    <a rel="tooltip" data-placement="bottom" data-html="true"
                                       data-original-title="{{ staff.personal_email }}"
                                       href="mailto:{{ staff.personal_email }}">
                                        {{ staff.personal_email | truncatechars:30 }}
                                    </a>
                                </td>
                                <td>
                                    <span rel="tooltip" data-placement="bottom" data-html="true"
                                          data-original-title="{{ staff.team.team_name }}">
                                        {{ staff.team.team_name | truncatechars:30 }}
                                    </span>
                                </td>
                                <td>
                                    <span rel="tooltip" data-placement="bottom" data-html="true" class="txt-color-orangeDark"
                                          data-original-title="{{ staff.get_active_position_desc }}">
                                        {{ staff.get_active_position_desc | truncatechars:30 }}
                                    </span>
                                </td>
                                <td>
                                    <span class="{% user_status_bg_class staff=staff %}">
                                        {{ staff.get_status_display }}
                                    </span>
                                </td>
                                <td>
                                    {% staff_action_html staff=staff request=request %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tab-pane" id="s2">
                <div class="row">
                    <div class="col-sm-6"><h5>Active Staff Only</h5></div>
                    {% if request|check_pv:'STAFF_CREATE'%}
                        <div class="col-sm-6">
                            <a href="{% url 'staff_create' %}" class="button button-flat-primary pull-right mb5"><i class="fa fa-plus f11p" aria-hidden="true"></i> Create Staff</a>
                        </div>
                    {% endif %}
                </div>

                <div class="tree ml20 mt5">
                    {% make_staff_tree request %}
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


{% block jscript %}
<script>

$(function(){

    var table_id = '#content-table';
    JLib.init_data_table(table_id, true, 'search-input');
    JLib.keep_tab_status('tab-head', 'staff_index_tab');

    $('select[name="team"]').change(function() {
        window.location = $(this).val();
    });

})
</script>

<script src="{{ STATIC_URL }}js/staff_action.js?version=1.0.0"></script>

{% endblock %}