core/urls.py
from django.conf.urls import url

from core.views import DashboardView, StaffTeamIndexView, StaffTeamCreateView, StaffTeamEditView, StaffTeamDeleteView, \
    StaffIndexView, StaffDetailView, StaffCreateView, StaffEditView, StaffInactiveView, StaffActiveView, \
    StaffChangePasswordView, MyProfileEditView, StaffDeleteView
from my_tools.decorators import back_login_required, check_staff_perm
from myhestia.privilege_const import STAFF_VIEW, STAFF_CREATE, STAFF_TEAM_VIEW, STAFF_TEAM_CREATE


urlpatterns = [
    #
    # /back-office/home
    #
    url(r'^$', back_login_required(check_staff_perm([])(DashboardView.as_view())), name='home'),

    #
    # business team
    #
    url(r'^staff-team/$',
        back_login_required(check_staff_perm([STAFF_TEAM_VIEW])(StaffTeamIndexView.as_view())),
        name='staff_team_index'),
    url(r'^staff-team/create/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamCreateView.as_view())),
        name='staff_team_create'),
    url(r'^staff-team/edit/(?P<team_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamEditView.as_view())),
        name='staff_team_edit'),
    url(r'^staff-team/delete/(?P<team_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_TEAM_CREATE])(StaffTeamDeleteView.as_view())),
        name='staff_team_delete'),

    #
    # staff
    #
    url(r'^staff/$',
        back_login_required(check_staff_perm([STAFF_VIEW])(StaffIndexView.as_view())),
        name='staff_index'),
    url(r'^staff-detail/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_VIEW])(StaffDetailView.as_view())),
        name='staff_detail'),
    url(r'^staff/create/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffCreateView.as_view())),
        name='staff_create'),
    url(r'^staff/edit/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffEditView.as_view())),
        name='staff_edit'),
    url(r'^staff/inactive/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffInactiveView.as_view())),
        name='staff_inactive'),
    url(r'^staff/active/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffActiveView.as_view())),
        name='staff_active'),
    url(r'^staff/delete/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([STAFF_CREATE])(StaffDeleteView.as_view())),
        name='staff_delete'),

    # change password for me or other staff
    url(r'^staff/change-password/(?P<user_id>\d+)/$',
        back_login_required(check_staff_perm([])(StaffChangePasswordView.as_view())),
        name='staff_change_password'),

    # edit my profile
    url(r'^staff/my-edit/$',
        back_login_required(check_staff_perm([])(MyProfileEditView.as_view())),
        name='my_profile_edit'),

]

myhestia/urls.py
from django.contrib import admin
from django.conf import settings
from core.views import upload, view_file
from django.conf.urls import include, url
from django.views.static import serve
from django.conf.urls.static import static
from login.views import login_view, login_check, login_out


#
# common URL
#
urlpatterns = [

    url(r'^admin/', admin.site.urls),

    #
    #  media file
    #
    url(r'^media/(?P<path>.*)$', serve, {'document_root': 'media/'}),

    #
    # file upload, download
    #
    url(r'^upload/$', upload, name='upload'),
    url(r'^view-file/(?P<file_uuid>[a-fA-F0-9]{32})/$', view_file, name='view_file'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)


#
# APP URL
#
urlpatterns += [

    #
    # index page
    #
    url(r'^$', login_view, name='index'),

    #
    # login/logout
    #
    url(r'^login/$', login_view, name='login'),
    url(r'^login_check/$', login_check, name='login_check'),
    url(r'^logout/$', login_out, name='logout'),

    #
    # dashboard
    #
    url(r'^home/', include('core.urls')),

    # agent
    url(r'^agent/', include('agent.urls')),

    # client
    url(r'^client/', include('clientdb.urls')),

    # matter
    url(r'^matter/', include('matters.urls')),

    # project
    url(r'^project/', include('project.urls')),

    # notification template
    url(r'^n-template/', include('n_template.urls')),

    #
    url(r'^report/', include('my_report.urls')),

    # bill
    url(r'^bill/', include('my_bill.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

n_template/urls.py
from django.conf.urls import url
from myhestia.privilege_const import NOTIFICATION_VIEW, NOTIFICATION_CREATE
from my_tools.decorators import check_staff_perm, back_login_required
from n_template.views import NTemplateIndexView, NTemplateDetailView, NTemplatePreviewView, NTemplateEditView, \
    NTemplateInactiveView, NTemplateActiveView


urlpatterns = [

    #
    # n-template/
    #
    url(r'^template/$',
        back_login_required(check_staff_perm([NOTIFICATION_VIEW])(NTemplateIndexView.as_view())),
        name='n_template_index'),

    url(r'^template/detail/(?P<template_id>\d+)/$',
        back_login_required(check_staff_perm([NOTIFICATION_VIEW])(NTemplateDetailView.as_view())),
        name='n_template_detail'),

    url(r'^template/preview/(?P<template_id>\d+)/$',
        back_login_required(check_staff_perm([NOTIFICATION_VIEW])(NTemplatePreviewView.as_view())),
        name='n_template_preview'),


    url(r'^template/edit/(?P<template_id>\d+)/$',
        back_login_required(check_staff_perm([NOTIFICATION_CREATE])(NTemplateEditView.as_view())),
        name='n_template_edit'),
    url(r'^template/inactive/(?P<template_id>\d+)/$',
        back_login_required(check_staff_perm([NOTIFICATION_CREATE])(NTemplateInactiveView.as_view())),
        name='n_template_inactive'),
    url(r'^template/active/(?P<template_id>\d+)/$',
        back_login_required(check_staff_perm([NOTIFICATION_CREATE])(NTemplateActiveView.as_view())),
        name='n_template_active'),
]

n_template/models.py
from __future__ import unicode_literals
from django.db import models
from django.template.defaultfilters import pluralize
from n_template.common import NConst


class NTemplate(models.Model):

    STATUS_ACTIVE = 'A'
    STATUS_INACTIVE = 'IA'
    STATUS_CHOICE = ((STATUS_ACTIVE, 'In Use'), (STATUS_INACTIVE, 'Not In Use'))

    TRIGGER_EXCHANGE = 'EXC'
    TRIGGER_SETTLEMENT = 'SET'
    TRIGGER_STAMP_DUTY_DUE = 'SDD'
    TRIGGER_CHOICE = (
        (TRIGGER_EXCHANGE, 'Contract Exchange'), (TRIGGER_STAMP_DUTY_DUE, 'Stamp Duty Due'),
        (TRIGGER_SETTLEMENT, 'Settlement')
    )

    CATEGORY_MATTER_PURCHASE_OFF_PLAN = 'MPO'
    CATEGORY_MATTER_PURCHASE_EXISTING = 'MPE'
    CATEGORY_MATTER_SALE_EXISTING = 'MSE'
    CATEGORY_CHOICE = (
        (CATEGORY_MATTER_PURCHASE_OFF_PLAN, 'Purchase Off-Plan Property (Matter)'),
        (CATEGORY_MATTER_PURCHASE_EXISTING, 'Purchase Existing Property (Matter)'),
        (CATEGORY_MATTER_SALE_EXISTING, 'Sell Existing Property (Matter)'),
    )

    template_name = models.CharField(max_length=64, default='', unique=True)
    status = models.CharField(max_length=8, blank=True, default=STATUS_ACTIVE, choices=STATUS_CHOICE)

    # email or sms
    send_type = models.CharField(max_length=4, default=NConst.SEND_TYPE_EMAIL, choices=NConst.SEND_TYPE_CHOICE)

    # bind template to generate notification instance
    category = models.CharField(max_length=8, choices=CATEGORY_CHOICE, default='', blank=True)

    #
    trigger = models.CharField(max_length=8, choices=TRIGGER_CHOICE, default='', blank=True)

    # 0 - on the day, - before, + after
    trigger_days = models.SmallIntegerField(default=0)

    subject = models.CharField(max_length=128, blank=True, default='')
    content = models.TextField()

    # attachment types
    attachments = models.ManyToManyField('AttachmentType', related_name='attachment_n_templates', blank=True)

    send_tos = models.ManyToManyField('NReceiver', related_name='send_to_n_templates', blank=True)
    cc_tos = models.ManyToManyField('NReceiver', related_name='cc_to_n_templates', blank=True)

    def __unicode__(self):
        return self.template_name

    def get_trigger_desc(self):
        if self.trigger_days == 0:
            return "On The Day of %s" % self.get_trigger_display()

        elif self.trigger_days < 0:
            _days = abs(self.trigger_days)
            return "%s day%s Before %s" % (_days, pluralize(_days), self.get_trigger_display(),)

        return "%s day%s After %s" % (self.trigger_days, pluralize(self.trigger_days), self.get_trigger_display(),)

    def get_attachment_desc(self):
        return ", ".join([a.get_type_name_display() for a in self.attachments.all()])


class AttachmentType(models.Model):

    TYPE_CONTRACT = 'Contract'
    TYPE_DEED = 'Deed'
    TYPE_NOTICE = 'Notice'
    TYPE_LETTER = 'Letter'

    TYPE_CHOICE = (
        (TYPE_CONTRACT, TYPE_CONTRACT), (TYPE_DEED, TYPE_DEED), (TYPE_NOTICE, TYPE_NOTICE), (TYPE_LETTER, TYPE_LETTER),
    )

    CATEGORY_MATTER = 'M'
    CATEGORY_CHOICE = (
        (CATEGORY_MATTER, 'Matter'),
    )

    # only matter now - v1.0.0
    category = models.CharField(max_length=1, default=CATEGORY_MATTER, choices=CATEGORY_CHOICE)
    type_name = models.CharField(max_length=64, choices=TYPE_CHOICE)

    def __unicode__(self):
        return "ID: %s Type: %s" % (self.pk, self.get_type_name_display(),)

    def map2_matter_doc_type(self):
        from matters.models import MatterDocument
        _mapping = {
            self.TYPE_CONTRACT: MatterDocument.TYPE_CONTRACT,
            self.TYPE_DEED: MatterDocument.TYPE_DEED,
            self.TYPE_NOTICE: MatterDocument.TYPE_NOTICE,
            self.TYPE_LETTER: MatterDocument.TYPE_LETTER,
        }

        return _mapping.get(self.type_name, '')


class NReceiver(models.Model):

    RECEIVER_CLIENT = 'Client'
    RECEIVER_STAFF = 'Staff'
    RECEIVER_AGENT = 'Agent'
    RECEIVER_SOLICITOR = 'Solicitor/Conveyancer'

    RECEIVER_CHOICE = (
        (RECEIVER_CLIENT, RECEIVER_CLIENT), (RECEIVER_STAFF, RECEIVER_STAFF), (RECEIVER_AGENT, RECEIVER_AGENT),
        (RECEIVER_SOLICITOR, RECEIVER_SOLICITOR),
    )

    CATEGORY_MATTER = 'M'
    CATEGORY_CHOICE = (
        (CATEGORY_MATTER, 'Matter'),
    )

    # only matter now - v1.0.0
    category = models.CharField(max_length=1, default=CATEGORY_MATTER, choices=CATEGORY_CHOICE)
    receiver = models.CharField(max_length=64, choices=RECEIVER_CHOICE)

    def __unicode__(self):
        return "ID: %s Receiver: %s" % (self.pk, self.get_receiver_display(),)

n_template/forms.py
from __future__ import unicode_literals
from django import forms
from django.db.models import Q
from django.forms import ModelForm
from n_template.common import NConst
from n_template.models import NTemplate, NReceiver, AttachmentType


class NTemplateEditForm(ModelForm):

    attachments = forms.ModelMultipleChoiceField(queryset=None, required=False)
    send_tos = forms.ModelMultipleChoiceField(queryset=None)
    cc_tos = forms.ModelMultipleChoiceField(queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        self.staff = kwargs.pop('staff')
        self.NTemplate = NTemplate
        self.NConst = NConst
        super(NTemplateEditForm, self).__init__(*args, **kwargs)

        self.receivers = NReceiver.objects.order_by('receiver')
        self.attach_types = AttachmentType.objects.order_by('type_name')

        self.fields['send_tos'].queryset = self.receivers
        self.fields['send_tos'].initial = [str(r.pk) for r in self.instance.send_tos.all()]

        self.fields['cc_tos'].queryset = self.receivers
        self.fields['cc_tos'].initial = [str(r.pk) for r in self.instance.cc_tos.all()]

        self.fields['attachments'].queryset = self.attach_types
        self.fields['attachments'].initial = [str(a.pk) for a in self.instance.attachments.all()]

    def clean_template_name(self):
        template_name = self.cleaned_data.get('template_name', '').strip()
        # unique
        if NTemplate.objects.filter(Q(template_name=template_name) & ~Q(pk=self.instance.pk)).exists():
            raise forms.ValidationError('Template name "%s" has already existed.' % template_name)
        return template_name

    def clean(self):
        return self.cleaned_data

    def save(self, force_insert=False, force_update=False, commit=True):

        send_tos = self.cleaned_data.get('send_tos', [])
        cc_tos = self.cleaned_data.get('cc_tos', [])
        attachments = self.cleaned_data.get('attachments', [])

        t = super(NTemplateEditForm, self).save(commit=False)
        t.save()

        # add send_tos
        t.send_tos.clear()
        t.send_tos.add(*send_tos)

        # add cc_tos
        t.cc_tos.clear()
        t.cc_tos.add(*cc_tos)

        # add attachments
        t.attachments.clear()
        t.attachments.add(*attachments)

        return t

    class Meta:
        model = NTemplate
        fields = [
            'subject', 'content',
        ]

n_template/views.py
from __future__ import unicode_literals
import json
from django.contrib import messages
from django.core.serializers.json import DjangoJSONEncoder
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import Template, Context
from django.urls import reverse
from django.views.generic import TemplateView
from my_tools.message import MyNotice
from n_template.common import NConst
from n_template.forms import NTemplateEditForm
from n_template.models import NTemplate


class NTemplateIndexView(TemplateView):

    template_name = 'n_template/template_index.html'

    def get(self, request, *args, **kwargs):

        templates = NTemplate.objects.all()

        data = {
            'templates': templates,
        }

        return render(request, self.template_name, data)

    def post(self, request):
        _ = self, request
        raise Http404('Page does not exist')


class NTemplateDetailView(TemplateView):

    template_name = 'n_template/template_detail.html'

    def get(self, request, *args, **kwargs):

        template_id = kwargs.get('template_id', 0)
        nt = get_object_or_404(NTemplate, pk=template_id)

        data = {
            'nt': nt,
            'NConst': NConst,
        }

        return render(request, self.template_name, data)

    def post(self, request):
        _ = self, request
        raise Http404('Page does not exist')


class NTemplatePreviewView(TemplateView):

    def get(self, request, *args, **kwargs):

        template_id = self.kwargs.get('template_id', 0)
        nt = get_object_or_404(NTemplate, pk=template_id)

        data = MyNotice.make_matter_notification_data(mn=None)

        html_content = Template(nt.content).render(Context(data))

        return HttpResponse(html_content)

    def post(self, request):
        _ = self, request
        raise Http404('Page does not exist')


class NTemplateEditView(TemplateView):

    template_name = 'n_template/template_edit.html'

    def get(self, request, *args, **kwargs):

        template_id = self.kwargs.get('template_id', 0)
        t = get_object_or_404(NTemplate, pk=template_id)

        form = NTemplateEditForm(staff=request.user, instance=t)

        data = {'form': form}

        return render(request, self.template_name, data)

    def post(self, request, template_id):

        t = get_object_or_404(NTemplate, pk=template_id)

        form = NTemplateEditForm(staff=request.user, data=request.POST, instance=t)

        data = {'form': form}

        # validate failed
        if not form.is_valid():
            return render(request, self.template_name, data)

        t = form.save()

        messages.success(request, "Template '%s' is updated" % t.template_name)

        return HttpResponseRedirect(reverse('n_template_detail', args=[t.pk]))


class NTemplateInactiveView(TemplateView):

    """
        ajax post
    """
    def get(self, request, *args, **kwargs):
        raise Http404('Page does not exist')

    def post(self, request, template_id):
        _ = self

        if not request.is_ajax() or template_id == 0:
            raise Http404("Page not exists")

        data = {'status': 'ok'}

        t = get_object_or_404(NTemplate, id=template_id)

        NTemplate.objects.filter(pk=template_id).update(status=NTemplate.STATUS_INACTIVE)

        msg = "Template '%s' is inactivated. This template will not be used to generate notification anymore. " \
              "Existing active notifications will still be sent out on scheduled time" % t.template_name
        messages.success(request, msg)

        return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')


class NTemplateActiveView(TemplateView):

    """
        ajax post
    """
    def get(self, request, *args, **kwargs):
        raise Http404('Page does not exist')

    def post(self, request, template_id):
        _ = self

        if not request.is_ajax() or template_id == 0:
            raise Http404("Page not exists")

        data = {'status': 'ok'}

        t = get_object_or_404(NTemplate, id=template_id)

        NTemplate.objects.filter(pk=template_id).update(status=NTemplate.STATUS_ACTIVE)

        messages.success(request, "Template '%s' is activated." % t.template_name)

        return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')

templates/n_template/template_create.html
{% extends 'mainbase.html' %}

{% block title %} Create Notification Template {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb_url 'Notification Template' 'n_template_index' %}
    {% breadcrumb 'Create Notification Template' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Create Notification Template
        <i class="pull-right f11p mt5"><span class="txt-color-red">* </span>compulsory fields</i>
    </h4>
    <hr class="dash mt5">

    <form action="{% url 'notice_template_create' %}" enctype="multipart/form-data" method="post" id='frm'>
        {% csrf_token %}

        <div class="form-group row">
            <div class="col-sm-3 control-group">
                <label for="template_name"><span class="txt-color-red">* </span>Template Name</label>
                <input type="text" name="template_name" class="form-control"
                       value="{{ form.template_name.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="64">
            </div>
            <div class="col-sm-3 control-group">
                <label for="category"><span class="txt-color-red">* </span>Template Type</label>
                <select type="text" name="category" class="form-control">
                    {% for k, v in form.NTemplate.TYPES %}
                        <option value="{{ k }}" {% if form.category.value == k %}selected{% endif %}>{{ v }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-3 control-group">
                <label for="trigger"><span class="txt-color-red">* </span>Trigger</label>
                <select type="text" name="trigger" class="form-control">
                    {% for k, v in form.NTemplate.TRIGGERS %}
                        <option value="{{ k }}" {% if form.trigger.value == k %}selected{% endif %}>{{ v }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-3 control-group">
                <label for="trigger_days"><span class="txt-color-red">* </span>Trigger Leading Days</label>
                <input type="text" name="trigger_days" class="form-control"
                       value="{{ form.trigger_days.value | default:'0'}}"
                       data-bv-notempty="true">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-6 control-group">
                <label for="subject"><span class="txt-color-red">* </span>Subject</label>
                <input type="text" name="subject" class="form-control"
                       value="{{ form.subject.value | default:''}}"
                       data-bv-notempty="true"
                       data-bv-stringlength="true" maxlength="128">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-2 control-group">
                <label for="send_to"><span class="txt-color-red">* </span>Send To</label>
                <select type="text" name="send_to" class="form-control">
                    {% for k, v in form.NTemplate.SEND_TOS %}
                        <option value="{{ k }}" {% if form.send_to.value == k %}selected{% endif %}>{{ v }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-2 control-group">
                <label class="checkbox-inline mt30">
                    <input type="checkbox" name='cc_agent' class="check-group" {% if form.cc_agent.value %}checked{% endif %}>
                    CC Agent
                </label>
            </div>
            <div class="col-sm-2 control-group">
                <label class="checkbox-inline mt30">
                    <input type="checkbox" name='cc_staff' class="check-group" {% if form.cc_staff.value %}checked{% endif %}>
                    CC Staff
                </label>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6">
                <label for="content"><span class="txt-color-red">* </span>Content</label>
                <textarea name='content' class="form-control" placeholder="" rows="4"
                        >{{ form.content.value | default:''}}</textarea>
            </div>
        </div>



        <div class="form-actions">
            <div class="row">
                <div class="col-md-12">
                    <button class="button button-flat-primary" type="submit">
                        Create Template
                    </button>
                </div>
            </div>
        </div>

    </form>
</div>


{% endblock %}


{% block jscript %}

<script>

$(function(){
    /**
     * form validation
     */
    $('#frm').bootstrapValidator({
        trigger: 'change keyup',
        group: '.control-group'
    });

})

</script>


{% endblock %}

templates/n_template/template_detail.html
{% extends 'mainbase.html' %}
{% load humanize %}

{% block title %} Template Detail {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb_url 'Notification Template' 'n_template_index' %}
    {% breadcrumb 'Template Detail' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">
        Template Detail
        <span class="pull-right">
            {% n_template_action_html nt=nt request=request html_type='btn' %}
        </span>
    </h4>
    <hr class="dash mt15">

    <div class="row detail-panel">
        <div class="col-sm-12">
            <dl class="dl-horizontal">
                <dt>ID</dt>
                <dd>
                    {{ nt.pk }}
                    <span class="{% n_template_status_bg_class nt=nt %} ml5">
                        {{ nt.get_status_display }}
                    </span>
                </dd>
                <dt>Template Name</dt>
                <dd class="txt-color-green"><b>{{ nt.template_name }}</b></dd>
                <dt>Category</dt>
                <dd>
                    <span class="{% n_template_category_class nt=nt %}">
                        {{ nt.get_category_display }}
                    </span>
                </dd>
                <dt>Send Type</dt>
                <dd class="{% send_type_class send_type=nt.send_type %}">{{ nt.get_send_type_display }}</dd>
                <dt>Trigger</dt>
                <dd>{{ nt.get_trigger_desc }}</dd>
                <dt>Send To</dt>
                <dd>{% n_template_send_to_html nt=nt %}</dd>

                {% if nt.send_type == NConst.SEND_TYPE_EMAIL %}
                    <dt>Subject</dt>
                    <dd>{{ nt.subject }}</dd>
                    <dt>Attachment</dt>
                    <dd>{{ nt.get_attachment_desc }}</dd>
                {% endif %}
                <dt>Content</dt>
                <dd>{{ nt.content|safe }}</dd>
            </dl>
        </div>
    </div>

</div>

{% endblock %}


{% block jscript %}

<script>

$(function(){

})

</script>

<script src="{{ STATIC_URL }}js/n_template_action.js?version=1.0.0.0"></script>

{% endblock %}

templates/n_template/template_index.html
{% extends 'mainbase.html' %}

{% block title %} Notification Template {{ block.super }} {% endblock %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'home' %}
    {% breadcrumb 'Notification Template' %}
{% endblock %}

{% block content %}

<div class="plain-panel">
    <h4 class="">Notification Template</h4>
    <hr class="dash mt10">

    <div class="row">
        <div class="col-lg-2 col-md-3 col-sm-4 pr0">
            <div class="input-icon-right">
                <i class="glyphicon glyphicon-search"></i>
                <input type="text" id="search-input" name="search" class="form-control" placeholder="Template Name">
            </div>
        </div>
    </div>

    <div class="mt10 table-responsive">
        <table class="table table-striped my-table" id="n-template-table" width="100%">
            <thead>
                <tr class="">
                    <th class="unsearchable">ID</th>
                    <th class="">Name</th>
                    <th class="unsearchable">Category</th>
                    <th class="unsearchable">Trigger</th>
                    <th class="unsearchable unsorted text-center">Type</th>
                    <th class="unsearchable unsorted">Send To</th>
                    <th class="unsearchable unsorted">Attachment</th>
                    <th class="unsearchable unsorted">Status</th>
                    <th class="unsearchable unsorted text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for nt in templates %}
                    <tr>
                        <td>{{ nt.pk }}</td>
                        <td>
                            <a href="{% url 'n_template_detail' template_id=nt.pk %}">{{ nt.template_name }}</a>
                        </td>
                        <td>
                            <span class="{% n_template_category_class nt=nt %}">
                                {{ nt.get_category_display }}
                            </span>
                        </td>
                        <td>{{ nt.get_trigger_desc }}</td>
                        <td class="{% send_type_class send_type=nt.send_type %} text-center">
                            {{ nt.get_send_type_display }}
                        </td>
                        <td>
                            {% n_template_send_to_html nt=nt %}
                        </td>
                        <td class="">
                            <span rel="tooltip" data-placement="bottom" data-html="true"
                                  data-original-title="{{ nt.get_attachment_desc }}">
                                {{ nt.get_attachment_desc|truncatechars:30 }}
                            </span>
                        </td>
                        <td>
                            <span class="{% n_template_status_bg_class nt=nt %}">
                                {{ nt.get_status_display }}
                            </span>
                        </td>
                        <td class="text-center">
                            {% n_template_action_html nt=nt request=request %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock %}


{% block jscript %}
<script>

$(function(){

    JLib.init_data_table('#n-template-table', true, 'search-input');

})
</script>

<script src="{{ STATIC_URL }}js/n_template_action.js?version=1.0.0.0"></script>

{% endblock %}